// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import NestedRondoController from "./nested_rondo_controller"
application.register("nested-rondo", NestedRondoController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
