version: '3.1'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
  js:
    build: .
    command: yarn build --watch
    tty: true
    volumes:
      - .:/usr/src/app
  css:
    build: .
    command: yarn build:css --watch
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=moodopus
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle:
